#!/usr/bin/env python3
"""ruah scanner: extract a code + infrastructure graph from a repository.

Usage:
  scan.py [REPO] [--out DIR] [--depth N] [--max-modules N]
          [--live aws,gcp,azure,k8s] [--aws-region R] [--gcp-project P] [--json]

Writes DIR/model.json (default DIR = REPO/.ruah) and prints a compact,
token-friendly summary meant to be read by Claude for the enrichment step.
Only stdlib is required (PyYAML is used if present).
"""
import argparse
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ruah_lib.code import CodeScanner  # noqa: E402
from ruah_lib.infra import InfraScanner  # noqa: E402
from ruah_lib.model import Model, list_files  # noqa: E402


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("repo", nargs="?", default=".")
    ap.add_argument("--out", help="output directory (default: REPO/.ruah)")
    ap.add_argument("--depth", type=int, default=2, help="module grouping depth inside a package (default 2)")
    ap.add_argument("--max-modules", type=int, default=40, help="max modules per package before collapsing depth")
    ap.add_argument("--live", default="", help="comma list of providers to query read-only: aws,gcp,azure,k8s")
    ap.add_argument("--aws-region")
    ap.add_argument("--gcp-project")
    ap.add_argument("--json", action="store_true", help="print full model JSON to stdout instead of a summary")
    args = ap.parse_args()

    root = os.path.abspath(args.repo)
    if not os.path.isdir(root):
        sys.exit(f"not a directory: {root}")
    out = os.path.abspath(args.out or os.path.join(root, ".ruah"))
    os.makedirs(out, exist_ok=True)
    gi = os.path.join(out, ".gitignore")
    if out.startswith(root + os.sep) and not os.path.exists(gi):
        with open(gi, "w") as f:
            f.write("# generated by ruah\n*\n")

    t0 = time.time()
    files = list_files(root)
    model = Model(root)
    code = CodeScanner(model, files, module_depth=args.depth, max_modules=args.max_modules).run()
    InfraScanner(model, files, code).run()
    live_report = None
    if args.live:
        from ruah_lib.live import discover
        live_report = discover(model, [p.strip() for p in args.live.split(",") if p.strip()],
                               aws_region=args.aws_region, gcp_project=args.gcp_project)

    data = model.to_json()
    data["scan"] = {"files": len(files), "seconds": round(time.time() - t0, 2), "live": live_report,
                    "options": {"depth": args.depth, "max_modules": args.max_modules}}
    path = os.path.join(out, "model.json")
    with open(path, "w") as f:
        json.dump(data, f, indent=1, default=list)

    if args.json:
        print(json.dumps(data, indent=1, default=list))
    else:
        print(summary(data, path))


def summary(d, path):
    nodes, edges = d["nodes"], d["edges"]
    by_id = {n["id"]: n for n in nodes}
    lines = [f"ruah model → {path}",
             f"repo: {d['repo']['name']}  files: {d['scan']['files']}  nodes: {len(nodes)}  edges: {len(edges)}  ({d['scan']['seconds']}s)",
             f"detectors: {', '.join(d['detectors'])}"]
    st = d["stack"]
    lines.append("languages: " + ", ".join(f"{k} {v}" for k, v in list(st["languages"].items())[:8]))
    if st["frameworks"]:
        lines.append("frameworks: " + ", ".join(st["frameworks"]))
    if st["package_managers"]:
        lines.append("tooling: " + ", ".join(st["package_managers"]))

    pkgs = [n for n in nodes if n["id"].startswith("pkg:")]
    lines.append(f"\n## code packages ({len(pkgs)})")
    for n in pkgs[:40]:
        mods = sum(1 for m in nodes if m.get("parent") == n["id"])
        meta = n.get("meta") or {}
        fw = ",".join(meta.get("frameworks", []))
        lines.append(f"- {n['id']}  [{n['kind']}] {n['label']}  modules={mods}" + (f"  fw={fw}" if fw else "")
                     + (f"  entry={meta['entrypoints'][0]}" if meta.get("entrypoints") else ""))
    if len(pkgs) > 40:
        lines.append(f"  … {len(pkgs) - 40} more")

    stacks = [n for n in nodes if n["id"].startswith("stack:") and n.get("layer") == "infra"]
    infra = [n for n in nodes if n.get("layer") == "infra" and not n["id"].startswith(("stack:", "plat:"))]
    lines.append(f"\n## infra ({len(infra)} resources in {len(stacks)} stacks; low-level hidden by default)")
    for s in stacks:
        kids = [n for n in infra if n.get("parent") == s["id"]]
        main = [n for n in kids if not n.get("low_level")]
        shown = ", ".join(f"{n['label']}({n['kind']})" for n in main[:10])
        lines.append(f"- {s['id']}: {len(kids)} resources ({len(kids) - len(main)} low-level) — {shown}"
                     + (" …" if len(main) > 10 else ""))
    plats = [n for n in nodes if n["id"].startswith("plat:")]
    if plats:
        lines.append("- platforms referenced only by CI: " + ", ".join(n["label"] for n in plats))

    exts = [n for n in nodes if n.get("layer") == "external"]
    if exts:
        lines.append(f"\n## external services ({len(exts)})")
        lines.append(", ".join(f"{n['label']}[{n.get('category')}]" for n in exts))

    ci = [n for n in nodes if n.get("layer") == "ci" and n["kind"] == "workflow"]
    if ci:
        lines.append(f"\n## ci/cd ({len(ci)})")
        for n in ci:
            targets = [by_id[e["target"]]["label"] for e in edges if e["source"] == n["id"]]
            lines.append(f"- {n['label']} ({n.get('file')})" + (f" → {', '.join(targets)}" if targets else ""))

    # what the enrichment step should look at
    linked = {e["target"] for e in edges if e["kind"] == "deploys_to"} | {e["source"] for e in edges if e["kind"] == "deploys_to"}
    unlinked = [n for n in infra if n["kind"] in ("function", "compute", "hosting") and n["id"] not in linked
                and n.get("status") != "live_only"]
    deployed_pkgs = {e["source"] for e in edges if e["kind"] == "deploys_to"}
    undeployed = [n for n in pkgs if n["kind"] in ("app", "service") and n["id"] not in deployed_pkgs
                  and not any(e["source"].startswith("mod:") and by_id.get(e["source"], {}).get("parent") == n["id"]
                              for e in edges if e["kind"] == "deploys_to")]
    lines.append("\n## gaps for enrichment")
    if unlinked:
        lines.append("- compute/function infra with no code link: " + ", ".join(n["id"] for n in unlinked[:25]))
    if undeployed:
        lines.append("- apps/services with no known deploy target: " + ", ".join(n["id"] for n in undeployed[:25]))
    if not (unlinked or undeployed):
        lines.append("- none detected")
    if d.get("env_keys"):
        lines.append("- env example files: " + ", ".join(d["env_keys"].keys()))
    if d["scan"].get("live"):
        lines.append("\n## live discovery")
        for p, r in d["scan"]["live"].items():
            lines.append(f"- {p}: {r}")
    if d["warnings"]:
        lines.append("\n## warnings")
        lines += [f"- {w}" for w in d["warnings"][:10]]
    return "\n".join(lines)


if __name__ == "__main__":
    main()
